version: "3"
services:
    api:
        build: .
        environment: 
            - EMAIL_API_KEY=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
        ports:
            - '8080:8080'
        volumes:
            - ./:/app
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379