version: "3"
services:
    api:
        build: .
        environment: 
            - EMAIL_API_KEY=${SENDGRID_API_KEY}
        ports:
            - '8080:8080'
        volumes:
            - ./:/app
    redis:
        image: redis
        container_name: cache
        expose:
            - 6379